language: clojure

script:
  - lein uberjar

deploy:
  provider: lambda
  function_name: NewReleasesBotLambda
  region: us-east-1
  role: arn:aws:iam::411928432103:role/lambda_basic_execution
  runtime: java8
  zip: target/uberjar/new-releases-slack-bot-0.1.0-SNAPSHOT-standalone.jar
  module_name: com.github.mindlessdrone
  handler_name: NewReleasesBot::handler
  timeout: 30
  memory_size: 512
  on:
    branch: fix-deployment
  secret_access_key:
    secure: j2Kkm1VgmKy0/sRcR+sok6n/YkEGaVd08dVr+Y3fqb0fl/CEVynW1FulTkuAvbfH/eqbdarw59hLD6Cq2kwr/64WJmlwU1O/+N7yAVq5zz0kBc5MIju9R6KZGU8qhrDk58TJDVvwQLqiXVPlLuzynXA32wHmgwSxrpJ9avHvCNOtRNP6TDcqY0xDPdPJpg7JrSTJZnMnRFz0yUs4YoJvYWu5J1kIIxgEAzDndCUqtzjEBV8m2n3EdggLaCra+k9LuTLiISSf6oD9yh+B3owWzcIzV5xoCRZ7anpbpx6AC4PQjAeZbeCHxGCgHqdvAjiWGrRj1Px6YTEQ8LjQI3jb0eAxj46MgEuYstWwTXrbmI77gAQTF1eH8MGkpxIjNr964BUA2waVHtI5DTtM3/OQYLs1cvg60Ov+zmRAW0Xx87rPH5bJhaRrCGFpUzvHcBM0m8jbCTSy2oW2az7HPQ21gLv6xmkLCgjydP5gM+FWK0lUUcKK4SH1ppO0MgYndnO7ZJE3UXlCM+iQu2kQhH7ttRA544IGF0jhRCvqn51GS9gbaTuA2a44f2RsuNLuegsEWhxfC4ygvCqq9MQxtxqe6wO4tPMSJ8nGK0uz0y1a3ukCM7mw9gAYiqGamU8gGgcHZFoinMb789mqH1GSagmNAUo9++UQz76cJzAUkVp54Do=
  access_key_id:
    secure: Bi2idrmElX3X3o6uB1qYLvDJGSnqlT7hvb3GIhw3htxSyoY6qSRaH3SHRKcJu07hSxll8MqbhH3Np9nZyBfZG7MGXiC4s5j55511f/4WT/vYjMnBfaQJGXJczYMSbzhUqGR97X0p5VD4JuCNrvCIdm8n70u0jEtOW2XwuM5bTdWo1lsVhQVWMuaTo8d440t24lcmXggP0Vo7NH4lVdKPf5MEez+p34K//rdBeDfJgxy/NqOH0vc34JMa0bwwcQs1v4XEedhy5Kxcxm6vX6KdE/Cvx+WCejz6WC1ZGIEHnWypHIuRpiHn6SmwPgKBLlOXPdFWp0XecSM1XdS/FGGzsu1o9eG7nrIJ4OT3RGoLVyVYkUXXTzUZYTU85BCgByAIb5fqw4W7zT523rZhPj09W4l0xhWzXy/zL10lqZG7gFFsEE2AUbq3rNgfLn4WTiqj3V/aRtduXfDFx7/0FD0O3ZLbNh2TRUQhmcAZjOJG/j0M1Z4dN8xD6f21GmAe2dlI2BCxiylaSQlNdO4/NE67cPHKXmF/Ck83+6yPUoLySLrvjdpaFNGJsOAZM9M9P7Se/06AvESQyW1oMu4qvRB6SK7/3ZozO22NsiJKA2j2nMCg5sMbbjalJDPrc3u+7x62NdkZXATRxr1EYBTXoTzvXjUIFm6soh5Lquf80FHtsVU=
