language: clojure
install:
- pip install awscli --user
- pip install aws-sam-cli --user
script:
- lein test
- lein uberjar
- sam package --template-file template.yaml --s3-bucket new-releases-bot-bucket --output-template-file packaged.yaml
deploy:
  provider: script
  script: sam deploy --template-file /home/travis/build/mindlessdrone/new-releases-slack-bot/packaged.yaml --stack-name new-releases-slack-bot
  on:
    branch: switch-to-sub-modules
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: mFyrWGnmoLbFz1rOidDsGJTxvpqCnLilZU8tJ6eQGAbuWlndiB4yx2W/bz4TZtb6n+tMdBw4AigLHe6MWO15WC0zmuRrY9rtuFrV/33NuSVLOKXLv7gNd1Y4uV4NeA7SsboLMGabcQCLystq9WACosASP543FiCKkff4VOM3YfIpED/iG727u0l/azJ7P1prXvmVilxkpH4UQOdhTE3MkFO/cEZJ12f6zncg0jw34c3S7W+OGS5MXNMPmf/R3nMrbgRhfAASzBVQJ45IksoLFLzRGhULuMSXbQ0ApWJm/ptQ9rwQ7xjgVwuYRM1pt0WpAMBdPhfDQFaMLfZkY2nhV4WUwvgDflZ0mL9KUk+uBEpCwKmCerhcvTnBXpmZZ9eq8pQOt7JMlfeqbvnvKcOPxf8C9bwAufhrqGyJp2QdmC1xyBV1AFarPqtX1FYUjH1sG0M6YB88r0LWpum3rOkK0JD+zIFwq7pdyXeDPOagtc5u95kqjxo3yRqcDfddmyUDoQ+ZlVHRCgphfNkYMsAnv9pRZhDi3sOwqpgb7ELxW3MRsAXZGn75d3Z0Hy4g7sBwYG9AwnF4I3nRM3tdfJEmYuQ4/5yw6x3+MtIKA6AryBv8QGfq//yBs3eV684xqjjr7/6i8HqKlglxzGXL+u7xvsQ+CWrryLFmTGSVj9bVuNQ=
  - secure: ev7C+RRkn+/fNzpSetwXqxi/NFQdcRxASY/fty+kmo2sWn3MHreizeLXIVxWKY9WIsbdiVsNx0x7GFP2jmyjTBIgSNaqsg+bB0LJbiOyS7B18vOjBUcRPLt2mNAlxzDLRRwAM0a7mjX/I46wFvZ/vpDoBW9e5C5Xw4t2MzaHWBm7lhPnKewqdvM63wYQzcp7Xizun21tulXld1sRuSAUwUv7VDtNxeB5h7p83UkFcjQbAGZt4Mh3NE1d14YnxyNxEF3+YUc2KvQUuEGN49kok+sFat/mOoPKiNqhKmHztWuq9RFk2p6uwX+wYOGVcFoWZUhmqFK9Nh4MJHVMTY3+vFUmlFwlJYBmzC0PCuX/cm/sWEuKVNRvrTfKweIpauerDODPP/dD/ElQgutvC10+QiyWMh6+4IbQr41BuQT09XpUIkjgro44FHESbSZ40WzsHDWbPJhFV2+RDbplt4hbAvMBYJHyMy1daMVjL1jVIqqKTnHkcLjgPWpDBUkB9HtNVzS2RmXW8vG4xb1BHeg6qZWdilfBJrtwt9LtfTVIykRDg0CN+tDTpSwq3FTe/V+bj7AvtfVZOx2p+s9hl2LrC3Mp6Je7JAtWRILHiz8m/pruGAz29EwG2+C8To0a4H5fK2jcWMjuYsklggN5WoMFqoGL3DhRsN5+OqlJfTyT7eQ=
